# Generated by Django 2.2.2 on 2019-08-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Songs',
        ),
    ]
